-- begin INSPECTIONRECORD_DEFECT_TYPE
alter table INSPECTIONRECORD_DEFECT_TYPE add constraint FK_INSPECTIONRECORD_DEFECT_TYPE_CAUSE_JOB foreign key (CAUSE_JOB_ID) references INSPECTIONRECORD_JOB(ID)^
create index IDX_INSPECTIONRECORD_DEFECT_TYPE_CAUSE_JOB on INSPECTIONRECORD_DEFECT_TYPE (CAUSE_JOB_ID)^
-- end INSPECTIONRECORD_DEFECT_TYPE
-- begin INSPECTIONRECORD_INSPECTION_RECORD
alter table INSPECTIONRECORD_INSPECTION_RECORD add constraint FK_INSPECTIONRECORD_INSPECTION_RECORD_EMPLOYEE foreign key (EMPLOYEE_ID) references INSPECTIONRECORD_EMPLOYEE(ID)^
create index IDX_INSPECTIONRECORD_INSPECTION_RECORD_EMPLOYEE on INSPECTIONRECORD_INSPECTION_RECORD (EMPLOYEE_ID)^
-- end INSPECTIONRECORD_INSPECTION_RECORD

-- begin INSPECTIONRECORD_INSPECTION_RECORD_DEFECT_TYPE_LINK
alter table INSPECTIONRECORD_INSPECTION_RECORD_DEFECT_TYPE_LINK add constraint FK_IIRDTL_INSPECTION_RECORD foreign key (INSPECTION_RECORD_ID) references INSPECTIONRECORD_INSPECTION_RECORD(ID)^
alter table INSPECTIONRECORD_INSPECTION_RECORD_DEFECT_TYPE_LINK add constraint FK_IIRDTL_DEFECT_TYPE foreign key (DEFECT_TYPE_ID) references INSPECTIONRECORD_DEFECT_TYPE(ID)^
-- end INSPECTIONRECORD_INSPECTION_RECORD_DEFECT_TYPE_LINK
-- begin INSPECTIONRECORD_DEFECT_TYPE_JOB_LINK
alter table INSPECTIONRECORD_DEFECT_TYPE_JOB_LINK add constraint FK_IDTJL_JOB foreign key (JOB_ID) references INSPECTIONRECORD_JOB(ID)^
alter table INSPECTIONRECORD_DEFECT_TYPE_JOB_LINK add constraint FK_IDTJL_DEFECT_TYPE foreign key (DEFECT_TYPE_ID) references INSPECTIONRECORD_DEFECT_TYPE(ID)^
-- end INSPECTIONRECORD_DEFECT_TYPE_JOB_LINK
-- begin INSPECTIONRECORD_EMPLOYEE
create unique index IDX_INSPECTIONRECORD_EMPLOYEE_UNIQ_HT_EMPL_ID on INSPECTIONRECORD_EMPLOYEE (HT_EMPL_ID) ^
-- end INSPECTIONRECORD_EMPLOYEE
-- begin INSPECTIONRECORD_JOB
create unique index IDX_INSPECTIONRECORD_JOB_UNIQ_HT_JOB_ID on INSPECTIONRECORD_JOB (HT_JOB_ID) ^
-- end INSPECTIONRECORD_JOB
